language: python
python:
  - "3.6"

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="foodbapp.settings.travis"


services:
  - postgresql

script:
  - ./manage.py test